Update patch set 1
Patch Set 1:

This is the exception I am trying to address with this edge rule

javax.ws.rs.BadRequestException: Error calling A&AI. Request-Id=null Invalid input performing PUT_EDGE on cloud-infrastructure/cloud-regions/cloud-region/CloudOwner/lab-nfvi/tenants/tenant/c21ac28e8a4a49ceb4973541e802146d (msg=Required Edge-property not found in input data:org.onap.aai.edges.exceptions.EdgeRuleNotFoundException: No rule found for EdgeRuleQuery with filter params node type: tenant, node type: vf-module, type: COUSIN, isPrivate: false.) (ec=ERR.5.4.6107)


> Patch Set 1:
> 
> Is this change you raised needed for Guilin? We should not be updating the model this late, as code freeze is today, and even if I merged this change it would have to be staged, released, and charts updated for all the microservices that use schema service.

Patch-set: 1